apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: task
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
        - name: tasks-api
          image: eddie0228/kube-dep-tasks
          env:
            - name: MONGODB_CONNECTION_URI
              value: "mongodb+srv://max:w5Do7LMvIVCCEmpV@cluster0.usgek2b.mongodb.net/users?retryWrites=true&w=majority"
            - name: AUTH_API_ADDRESS
              # value: "auth-service.default:3000"
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: AUTH_API_ADDRESS
